"""llm_profiles

Revision ID: 4a06b4709402
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 00:49:35.587642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a06b4709402'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'role', name='uq_llm_profile_role')
    )
    op.create_index(op.f('ix_llm_profiles_tenant_id'), 'llm_profiles', ['tenant_id'], unique=False)
    # NOTE: autogenerate cannot model the partial UNIQUE index on
    # executions.idempotency_key (from a1b2c3d4e5f6) — leave it untouched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_llm_profiles_tenant_id'), table_name='llm_profiles')
    op.drop_table('llm_profiles')
    # ### end Alembic commands ###
